build(ceph-api): 重构 Dockerfile 并更新配置
-重构 Dockerfile，优化构建过程和运行环境
- 更新 application-dev.yaml 和 application-prod.yaml，修改 AWS S3 配置
-调整 logback-spring.xml，优化日志配置

diff --git a/ceph-api/Dockerfile b/ceph-api/Dockerfile
--- a/ceph-api/Dockerfile
+++ b/ceph-api/Dockerfile
@@ -1,34 +1,53 @@
+# 构建阶段
 FROM registry.cn-shanghai.aliyuncs.com/qtech/maven:3.6-jdk-8 AS builder
 
 WORKDIR /usr/src/app
+
+# 复制 pom.xml 和 settings.xml，利用缓存
 COPY ./pom.xml /usr/src/app/pom.xml
 COPY ./settings.xml /usr/src/app/settings.xml
-RUN mvn dependency:go-offline -s /usr/src/app/settings.xml
+
+# 下载依赖
+RUN mvn dependency:go-offline -s /usr/src/app/settings.xml || (echo "Qtech-Im dependency download failed" && exit 1)
+
+# 复制源代码
 COPY ./src /usr/src/app/src
-RUN mvn -f /usr/src/app/pom.xml clean package -DskipTests  -s /usr/src/app/settings.xml
 
-# 如果基础镜像中没有时区数据，需要安装 tzdata 包
-RUN apt-get update && apt-get install -y tzdata
+# 编译打包
+RUN mvn -f /usr/src/app/pom.xml clean package -DskipTests -s /usr/src/app/settings.xml dependency:resolve || (echo "Qtech-Im build failed" && exit 1) && \
+    rm -rf /root/.m2/repository
 
-# 设置时区为Asia/Shanghai
-ENV TZ=Asia/Shanghai
-RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
-
+# 运行阶段
 FROM registry.cn-shanghai.aliyuncs.com/kolenz/openjdk:8-jre-alpine-font
-LABEL maintainer=gaoolin@gmail.com
+ARG MAINTAINER_EMAIL
+LABEL maintainer=${MAINTAINER_EMAIL}
 
+# 设置时区为上海时间
+RUN apk add --no-cache tzdata && \
+    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
+    echo "Asia/Shanghai" > /etc/timezone && \
+    apk del tzdata
+
+# 环境变量
 ENV PARAMS="--server.port=8080"
+ENV LOG_PATH=/home/qtech/logs
+ENV SPRING_PROFILES_ACTIVE=prod
+ENV JAVA_OPTS="-Dloader.path=/home/libs/ -Dfile.encoding=utf8 -Djava.security.egd=file:/dev/./urandom -Xmx2048m -Xms2048m -Dlogging.file.path=${LOG_PATH}"
+
+# 创建日志目录
+RUN mkdir -p ${LOG_PATH} && chmod -R 777 ${LOG_PATH}
 
 EXPOSE 8080
 
+# 复制构建阶段的输出
 COPY --from=builder /usr/src/app/target/*.jar /home/app.jar
 COPY --from=builder /usr/src/app/target/libs /home/libs/
 
 WORKDIR /home
 
-# 设置时区为Asia/Shanghai
-ENV TZ=Asia/Shanghai
-RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
+# 健康检查
+HEALTHCHECK --interval=30s --timeout=30s --retries=5 \
+  CMD curl -f http://localhost:8080/actuator/health/status || exit 1
 
-# 指定了jvm启动的内存大小
-ENTRYPOINT ["/bin/sh", "-c", "java -Dloader.path=/home/libs/ -Dfile.encoding=utf8 -Djava.security.egd=file:/dev/./urandom -jar -Xmx2048m -Xms2048m /home/app.jar ${PARAMS}"]
+# 启动命令 指定了jvm启动的内存大小
+ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar /home/app.jar ${PARAMS} --spring.profiles.active=${SPRING_PROFILES_ACTIVE}"]
